# Generated by Django 5.2 on 2025-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='major',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='addmisson_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='年级'),
        ),
    ]
