# Generated by Django 5.2 on 2025-05-04 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_major_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='作业标题')),
                ('description', models.TextField(blank=True, verbose_name='作业描述')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='布置时间')),
                ('deadline', models.DateTimeField(verbose_name='截止时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_classworks', to=settings.AUTH_USER_MODEL, verbose_name='布置教师')),
            ],
            options={
                'verbose_name': '课堂作业',
                'verbose_name_plural': '课堂作业',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='作业内容')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='分数')),
                ('feedback', models.TextField(blank=True, verbose_name='教师评语')),
                ('classwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.classwork', verbose_name='课堂作业')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_works', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生作业提交',
                'verbose_name_plural': '学生作业提交',
                'ordering': ['-submitted_at'],
                'unique_together': {('classwork', 'student')},
            },
        ),
    ]
