# Generated by Django 5.2 on 2025-05-02 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='major',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default=2.5, max_length=100, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '教师')], default='student', max_length=10, verbose_name='身份'),
        ),
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(auto_now_add=True, verbose_name='签到日期')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='签到IP')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '签到记录',
                'verbose_name_plural': '签到记录',
                'unique_together': {('user', 'check_in_date')},
            },
        ),
    ]
