# Generated by Django 5.2 on 2025-05-03 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('location', models.CharField(max_length=100, verbose_name='上课地点')),
                ('time_start', models.TimeField(verbose_name='上课时间')),
                ('time_end', models.TimeField(verbose_name='下课时间')),
                ('week_days', models.CharField(help_text='以逗号分隔的数字，代表星期几，例如1,3,5', max_length=20, verbose_name='上课日期')),
                ('students', models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL, verbose_name='选课学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_code', models.CharField(max_length=6, verbose_name='签到码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('status', models.CharField(choices=[('active', '进行中'), ('expired', '已结束'), ('cancelled', '已取消')], default='active', max_length=10, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='签到说明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_checkins', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '签到活动',
                'verbose_name_plural': '签到活动',
            },
        ),
        migrations.CreateModel(
            name='StudentCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('status', models.CharField(choices=[('success', '正常'), ('late', '迟到'), ('absent', '缺勤')], default='success', max_length=10, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='签到位置')),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkin.checkin', verbose_name='签到活动')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生签到记录',
                'verbose_name_plural': '学生签到记录',
                'unique_together': {('check_in', 'student')},
            },
        ),
    ]
