# Generated by Django 5.2 on 2025-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='course',
        ),
        migrations.AddField(
            model_name='checkin',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='班级名称'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
