# Generated by Django 5.2 on 2025-05-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_remove_checkin_course_checkin_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcheckin',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentcheckin',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='学生姓名'),
        ),
    ]
